steps:  
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$TAG_NAME', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME:$TAG_NAME']
- name: ['gcr.io/cloud-builders/kubectl']
  args: ['apply','-f','dev/secrets.yaml']
- name: 'gcr.io/crazy-sprout/helm'
  args:
  - upgrade
  - --install
  - dev-env-hello
  - --namespace
  - dev
  - dev/
  - --set=image.repository=gcr.io/$PROJECT_ID/$REPO_NAME
  - --set=image.tag=$TAG_NAME
  
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-southeast1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=standard-cluster-1'
  - 'TILLERLESS=true'
  - 'TILLER_NAMESPACE=develop'