steps:  
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$TAG_NAME', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME:$TAG_NAME']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply','-f', 'helloword-deployment-example.yaml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-southeast1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=standard-cluster-1'
- name: 'gcr.io/cloud-builders/kubectl'
  agrs:
    -set
    -image
    -deployment 
    -hello-word-example=gcr.io/$PROJECT_ID/$REPO_NAME:$TAG_NAME