steps:  
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$TAG_NAME', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME:$TAG_NAME']
- name: 'gcr.io/crazy-sprout/helm'
  args:
  - upgrade
  - --install
  - hello-world
  - dev/
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-southeast1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=standard-cluster-1'
  - 'TILLERLESS=true'
  - 'TILLER_NAMESPACE=develop'