apiVersion: v1
kind: Secret
metadata:
  name: dev-secret
  namespace: dev
type: Opaque
data:
  service_account_key: eyBoZWxsbzogInNkZmFzZCIsCnBhc3N3b3JkOiAid2hhdCIgfQo=
  slack_token: c2ZmcnQ2NHQ3dWs=
  webhook_token: c2RmZGdlcnd3NGRoZ3NmNjQz